In [51]:
%pip install beautifulsoup4 requests

import requests

from bs4 import BeautifulSoup

# BeautifulSoup, web sayfalarından veri çekmek için yaygın olarak kullanılan bir kütüphanedir.

Requirement already satisfied: beautifulsoup4 in c:\users\msi-nb\appdata\local\programs\python\python312\lib\site-packages (4.12.3)
Requirement already satisfied: requests in c:\users\msi-nb\appdata\local\programs\python\python312\lib\site-packages (2.32.3)
Requirement already satisfied: soupsieve>1.2 in c:\users\msi-nb\appdata\local\programs\python\python312\lib\site-packages (from beautifulsoup4) (2.6)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\msi-nb\appdata\local\programs\python\python312\lib\site-packages (from requests) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\msi-nb\appdata\local\programs\python\python312\lib\site-packages (from requests) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\msi-nb\appdata\local\programs\python\python312\lib\site-packages (from requests) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\msi-nb\appdata\local\programs\python\python312\lib\site-packages (from requests) (2024.8.30)
Note: you may need to restart the kernel to use updated packages.

In [52]:
import pandas as pd

In [53]:
# https://www.hukuksorucevap.com.tr/sorucevap/?sayfa=1 adresindeki soru ve cevapları çekeceğiz. Toplamda 36 sayfa var.

In [54]:
response = requests.get('https://www.hukuksorucevap.com.tr/sorucevap/?sayfa=1')
response.encoding = 'utf-8'
response # <Response [200]> demek internete bağlandı. Başarılı.apparent_encoding

response.text # bunu yazınca butun yazıyı alabiliyoruz.

'\r\n<!DOCTYPE html>\r\n<html lang="tr-TR">\r\n<head>\r\n<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />\r\n<meta name="content-language" content="tr-TR" />\r\n<meta http-equiv="X-UA-Compatible" content="IE=edge">\r\n<meta name="viewport" content="width=device-width, initial-scale=1">\r\n\r\n<title>Soru & Cevap</title>\r\n<meta name="description" content="Ziyaretçilerimizin avukatlık ofisimize sordukları soruları cevapladığımız sayfa." />\r\n<meta name="robots" content="index,follow" />\r\n<link rel="canonical" href="https://www.hukuksorucevap.com.tr/sorucevap/?sayfa=1" />\r\n<link rel="shortcut icon" href="/images/favicon.ico" type="image/x-icon">\r\n \r\n\r\n<link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,600,700" rel="stylesheet"> \r\n\r\n<link rel="stylesheet" type="text/css" href="/css/stil.css?v=1.3" />\r\n<script type="text/javascript" src="/js/jquery.js"></script>\r\n\r\n<li style="display:none" id="google_translate_element2"></li>\r\n<script type="text/javascript">\r\nfunction googleTranslateElementInit2() {new google.translate.TranslateElement({pageLanguage: \'tr\',autoDisplay: false}, \'google_translate_element2\');}\r\n</script>\r\n<script type="text/javascript" src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit2"></script>\r\n\r\n<script type="text/javascript">\r\nfunction GTranslateGetCurrentLang() {var keyValue = document.cookie.match(\'(^|;) ?googtrans=([^;]*)(;|$)\');return keyValue ? keyValue[2].split(\'/\')[2] : null;}\r\nfunction GTranslateFireEvent(element,event){try{if(document.createEventObject){var evt=document.createEventObject();element.fireEvent(\'on\'+event,evt)}else{var evt=document.createEvent(\'HTMLEvents\');evt.initEvent(event,true,true);element.dispatchEvent(evt)}}catch(e){}}\r\nfunction doGTranslate(lang_pair){if(lang_pair.value)lang_pair=lang_pair.value;if(lang_pair==\'\')return;var lang=lang_pair.split(\'|\')[1];if(GTranslateGetCurrentLang() == null && lang == lang_pair.split(\'|\')[0])return;var teCombo;var sel=document.getElementsByTagName(\'select\');for(var i=0;i<sel.length;i++)if(sel[i].className==\'goog-te-combo\')teCombo=sel[i];if(document.getElementById(\'google_translate_element2\')==null||document.getElementById(\'google_translate_element2\').innerHTML.length==0||teCombo.length==0||teCombo.innerHTML.length==0){setTimeout(function(){doGTranslate(lang_pair)},500)}else{teCombo.value=lang;GTranslateFireEvent(teCombo,\'change\');GTranslateFireEvent(teCombo,\'change\')}}\r\nif(GTranslateGetCurrentLang() != null)jQuery(document).ready(function() {jQuery(\'div.switcher div.selected a\').html(jQuery(\'div.switcher div.option\').find(\'img[alt="\'+GTranslateGetCurrentLang()+\'"]\').parent().html());});\r\n</script>\r\n\r\n<!-- Google tag (gtag.js) -->\r\n<script async src="https://www.googletagmanager.com/gtag/js?id=AW-11400734304">\r\n</script>\r\n<script>\r\n  window.dataLayer = window.dataLayer || [];\r\n  function gtag(){dataLayer.push(arguments);}\r\n  gtag(\'js\', new Date());\r\n  gtag(\'config\', \'AW-11400734304\');\r\n</script>\r\n\r\n</head>\r\n<body>\r\n\r\n<!--Üst Blok Başlangıcı-->\r\n<div id="UstBlok">\r\n<div id="UstBlok_Ortala">\r\n\r\n<!--Diller Başlangıcı-->\r\n<div id="Diller_Mobil">\r\n<img src="/images/dil_tr.png" alt="Turkish" onclick="doGTranslate(\'tr|tr\');"/>\r\n<img src="/images/dil_en.png" alt="English" onclick="doGTranslate(\'tr|en\');"/>\r\n<img src="/images/dil_de.png" alt="Deutsch" onclick="doGTranslate(\'tr|de\');"/>\r\n</div>\r\n<!--/Diller Bitişi-->\r\n\r\n<!--Logo Başlangıcı-->\r\n<div id="Logo"><a href="/" title="Hukuk Bilgi Platformu"><img src="/images/logo.png" alt="Hukuk Bilgi Platformu"/></a></div>\r\n<!--/Logo Bitişi-->\r\n\r\n<!--Telefon Başlangıcı-->\r\n<div id="Telefon_Mobil"><a href="tel:0312 295 64 03" title="0312 295 64 03"></a></div>\r\n<!--/Telefon Bitişi-->\r\n\r\n<div id="Telefon_UstMenu">\r\n<!--Diller Başlangıcı-->\r\n<div id="Diller">\r\n<img src="/images/dil_tr.png" alt="Turkish" onclick="doGTranslate(\'tr|tr\');"/>\r\n<img src="/images/dil_en.png" alt="English" onclick="doGTranslate(\'tr|en\');"/>\r\n<img src="/images/dil_de.png" alt="Deutsch" onclick="doGTranslate(\'tr|de\');"/>\r\n</div>\r\n<!--/Diller Bitişi-->\r\n\r\n<div id="Sosyal_Telefon">\r\n<!--Sosyal Medya Başlangıcı-->\r\n<div id="Sosyal">\r\n<a href="" class="Facebook" title="Facebook" target="_blank"></a>\r\n<a href="" class="Instagram" title="Instagram" target="_blank"></a>\r\n<a href="" class="Youtube" title="Twitter" target="_blank"></a>\r\n</div>\r\n<!--/Sosyal Medya Bitişi-->\r\n\r\n<!--Telefon Başlangıcı-->\r\n<div id="Telefon">\r\n<div id="Tel_Icon"></div>\r\n<div id="Numara">0312 295 64 03</div>\r\n</div>\r\n<!--/Telefon Bitişi-->\r\n\r\n<!--Whatsapp Başlangıcı-->\r\n<div id="Telefon">\r\n<div id="Mail_Icon"></div>\r\n<div id="Numara">info@hukuksorucevap.com.tr</div>\r\n</div>\r\n<!--/Whatsapp Bitişi-->\r\n</div>\r\n\r\n<!--Üst Menü Başlangıcı-->\r\n<div id="UstMenu">\r\n<ul>\r\n<li><a href="/sistem/" class="ico_sistem" title="E-Müvekkil Girişi">E-Müvekkil Girişi</a></li>\r\n<li><a href="/fotogaleri/" class="ico_fotograflar" title="Fotoğraflar">Foto Galeri</a></li>\r\n<li><a href="/insankaynaklari/" class="ico_ik" title="İnsan Kaynakları">İnsan Kaynakları</a></li>\r\n<li><a href="/randevu/" class="ico_randevu" title="E-Randevu">E-Randevu</a></li>\r\n</ul>\r\n</div>\r\n<!--/Üst Menü Bitişi-->\r\n</div>\r\n\r\n</div>\r\n\r\n<!--Mobil Menü Buton Başlangıcı-->\r\n<div class="MobilMenuButon"><a href="#menu"></a>\r\n<span></span>\r\n<span></span>\r\n<span></span>\r\n<span></span>\r\n</div>\r\n<!--/Mobil Menü Buton Bitişi-->\r\n<!--Mobil Menü Başlangıcı-->\r\n<div id="MobilMenu">\r\n<nav id="menu">\r\n<ul>\r\n<li><a href="/" title=">Ana Sayfa">Ana Sayfa</a></li>\r\n<li><a href="/hakkimizda/" title="Hakkımızda">Hakkımızda</a></li>\r\n<li><a href="/sorucevap/" title="Soru & Cevap">Soru & Cevap</a></li>\r\n<li><a href="/sistem/" title="E-Müvekkil Girişi">E-Müvekkil Girişi</a></li>\r\n<li><a href="/fotogaleri/" title="Fotoğraflar">Foto Galeri</a></li>\r\n<li><a href="/insankaynaklari/" title="İnsan Kaynakları">İnsan Kaynakları</a></li>\r\n<li><a href="/randevu/" title="E-Randevu">E-Randevu</a></li>\r\n<li><a href="/iletisim/" title="İletişim Bilgilerimiz">İletişim Bilgilerimiz</a></li>\r\n</ul>\r\n</nav>\r\n</div>\r\n<!--/Mobil Menü Bitişi-->\r\n\t\t\t\r\n\r\n<!--Menü Başlangıcı-->\r\n<div id="Menu">\r\n<ul>\r\n<li><a href="/" title=">Ana Sayfa">Ana Sayfa</a></li>\r\n<div id="Menu_Ara_Cizgi"></div>\r\n<li><a href="/hakkimizda/" title="Hakkımızda">Hakkımızda</a></li>\r\n<div id="Menu_Ara_Cizgi"></div>\r\n<li><a href="/sorucevap/" title="Soru & Cevap">Soru & Cevap</a></li>\r\n<div id="Menu_Ara_Cizgi"></div>\r\n<li><a href="/iletisim/" title="İletişim Bilgilerimiz">İletişim Bilgilerimiz</a></li>\r\n</ul>\r\n</div>\r\n<!--/Menü Bitişi-->\r\n\r\n</div>\r\n<!--/Üst Blok Bitişi-->\r\n\r\n\r\n<!--Ortala Başlangıcı-->\r\n<div id="Ortala">\r\n\r\n<!--Detay Başlangıcı-->\r\n<div id="Detay">\r\n<script type="text/javascript">\r\nfunction formkontrol() {\r\nvar bilgi = document.getElementById("iletisimim");\r\nvar adi = bilgi.adi.value;\r\nvar mail = bilgi.mail.value;\r\nvar tel = bilgi.tel.value;\r\nvar sehir = bilgi.sehir.value;\r\nvar konu = bilgi.konu.value;\r\nvar soru = bilgi.soru.value;\r\nif(adi=="") {\r\nalert("Lütfen Adınız ve Soyadınız Alanını Doldurunuz !");\r\nbilgi.adi.focus();\r\nreturn false;\r\n}\r\nif(mail=="") {\r\nalert("Lütfen E-Mail Adresiniz Alanını Doldurunuz !");\r\nbilgi.mail.focus();\r\nreturn false;\r\n}\r\nif(tel=="") {\r\nalert("Lütfen Telefon Numaranız Alanını Doldurunuz !");\r\nbilgi.tel.focus();\r\nreturn false;\r\n}\r\nif(sehir=="") {\r\nalert("Lütfen Şehrinizi Seçiniz !");\r\nbilgi.sehir.focus();\r\nreturn false;\r\n}\r\nif(konu=="") {\r\nalert("Lütfen Konu Alanını Doldurunuz !");\r\nbilgi.konu.focus();\r\nreturn false;\r\n}\r\nif(soru=="") {\r\nalert("Lütfen Sorunuz Alanını Doldurunuz !");\r\nbilgi.soru.focus();\r\nreturn false;\r\n}\r\nbilgi.submit();\r\n}\r\n</script>\r\n\r\n<script type="text/javascript" src="/js/input_tel.js"></script>\r\n<script type="text/javascript">\r\n$(document).ready(function(){\r\n$("#tel").inputmask({"mask": "0(999) 999 99 99"});\r\n});\r\n</script>\r\n\r\n<h1 id="Detay_Baslik">Soru Sorun - Bilgi Sahibi Olun</h1>\r\n<div id="Detay_Icerik">\r\n\r\n<form method="post" action="" id="iletisimim" onSubmit="return formkontrol(this);">\r\n<div id="Rendevu_Formu" style="margin-left:0px;">\r\n<input type="text" name="adi" id="adi" class="input" placeholder="Adınız ve Soyadınız *"/>\r\n<input type="text" name="mail" id="mail" class="input" placeholder="E-Mail Adresiniz *"/>\r\n<input type="text" name="tel" id="tel" class="input" placeholder="Telefon Numaranız *"/>\r\n<select name="sehir" id="sehir" class="select">\r\n<option value="">Şehir Seçiniz *</option>\r\n<option value="İstanbul">İstanbul</option>\r\n<option value="Ankara">Ankara</option>\r\n<option value="İzmir">İzmir</option>\r\n<option value="Adana">Adana</option>\r\n<option value="Antalya">Antalya</option>\r\n<option value="Adıyaman">Adıyaman</option>\r\n<option value="Afyon">Afyon</option>\r\n<option value="Ağrı">Ağrı</option>\r\n<option value="Aksaray">Aksaray</option>\r\n<option value="Amasya">Amasya</option>\r\n<option value="Ardahan">Ardahan</option>\r\n<option value="Artvin">Artvin</option>\r\n<option value="Aydın">Aydın</option>\r\n<option value="Balıkesir">Balıkesir</option>\r\n<option value="Bartın">Bartın</option>\r\n<option value="Batman">Batman</option>\r\n<option value="Bayburt">Bayburt</option>\r\n<option value="Bilecik">Bilecik</option>\r\n<option value="Bingöl">Bingöl</option>\r\n<option value="Bitlis">Bitlis</option>\r\n<option value="Bolu">Bolu</option>\r\n<option value="Burdur">Burdur</option>\r\n<option value="Bursa">Bursa</option>\r\n<option value="Çanakkale">Çanakkale</option>\r\n<option value="Çankırı">Çankırı</option>\r\n<option value="Çorum">Çorum</option>\r\n<option value="Denizli">Denizli</option>\r\n<option value="Diyarbakır">Diyarbakır</option>\r\n<option value="Düzce">Düzce</option>\r\n<option value="Edirne">Edirne</option>\r\n<option value="Elazığ">Elazığ</option>\r\n<option value="Erzincan">Erzincan</option>\r\n<option value="Erzurum">Erzurum</option>\r\n<option value="Eskişehir">Eskişehir</option>\r\n<option value="Gaziantep">Gaziantep</option>\r\n<option value="Giresun">Giresun</option>\r\n<option value="Gümüşhane">Gümüşhane</option>\r\n<option value="Hakkari">Hakkari</option>\r\n<option value="Hatay">Hatay</option>\r\n<option value="Iğdır">Iğdır</option>\r\n<option value="Isparta">Isparta</option>\r\n<option value="Kahramanmaraş">Kahramanmaraş</option>\r\n<option value="Karabük">Karabük</option>\r\n<option value="Karaman">Karaman</option>\r\n<option value="Kars">Kars</option>\r\n<option value="Kastamonu">Kastamonu</option>\r\n<option value="Kayseri">Kayseri</option>\r\n<option value="Kırıkkale">Kırıkkale</option>\r\n<option value="Kırklareli">Kırklareli</option>\r\n<option value="Kırşehir">Kırşehir</option>\r\n<option value="Kilis">Kilis</option>\r\n<option value="Kocaeli">Kocaeli</option>\r\n<option value="Konya">Konya</option>\r\n<option value="Kütahya">Kütahya</option>\r\n<option value="Malatya">Malatya</option>\r\n<option value="Manisa">Manisa</option>\r\n<option value="Mardin">Mardin</option>\r\n<option value="Mersin">Mersin</option>\r\n<option value="Muğla">Muğla</option>\r\n<option value="Muş">Muş</option>\r\n<option value="Nevşehir">Nevşehir</option>\r\n<option value="Niğde">Niğde</option>\r\n<option value="Ordu">Ordu</option>\r\n<option value="Osmaniye">Osmaniye</option>\r\n<option value="Rize">Rize</option>\r\n<option value="Sakarya">Sakarya</option>\r\n<option value="Samsun">Samsun</option>\r\n<option value="Siirt">Siirt</option>\r\n<option value="Sinop">Sinop</option>\r\n<option value="Sivas">Sivas</option>\r\n<option value="Şanlıurfa">Şanlıurfa</option>\r\n<option value="Şırnak">Şırnak</option>\r\n<option value="Tekirdağ">Tekirdağ</option>\r\n<option value="Tokat">Tokat</option>\r\n<option value="Trabzon">Trabzon</option>\r\n<option value="Tunceli">Tunceli</option>\r\n<option value="Uşak">Uşak</option>\r\n<option value="Van">Van</option>\r\n<option value="Yalova">Yalova</option>\r\n<option value="Yozgat">Yozgat</option>\r\n<option value="Zonguldak">Zonguldak</option>\r\n</select> \r\n<input type="text" name="konu" id="konu" class="input" placeholder="Konu *"/>\r\n</div>\r\n\r\n<div id="Rendevu_Formu">\r\n<textarea name="soru" id="soru" class="textarea" placeholder="Sorunuz *" style="height:265px;"></textarea>\r\n</div>\r\n\r\n<span style="color:red; font-weight:bold;">Kişisel bilgileriniz tam ve doğru bir şekilde girilmediği sürece sorularınız cevaplanmayacaktır.</span>\r\n\r\n\r\n<!--//\r\n/* *******************************************************\r\nSoftware: Web Wiz CAPTCHA(TM) ver. \r\nInfo: http://www.WebWizCAPTCHA.com\r\nCopyright: (C)2005-2013 Web Wiz Ltd. All rights reserved\r\n******************************************************* */\r\n//-->\r\n<script language="javaScript">\r\nfunction reloadCAPTCHA() {\r\n\tdocument.getElementById(\'CAPTCHA\').src=\'/captcha/CAPTCHA_image.asp?\'+Date();\r\n}\r\n</script>           \r\n\r\n\r\n<div id="GuvenlikKutulari">\r\n<div><img src="/captcha/CAPTCHA_image.asp" id="CAPTCHA" width="120" height="50" style="-webkit-border-radius:5px; -moz-border-radius:5px; border-radius:5px;"/></div>\r\n<div><a href="javascript:reloadCAPTCHA();" title="Yenile"><img src="/captcha/images/refresh.png" alt="Yenile" style="-webkit-border-radius:5px; -moz-border-radius:5px; border-radius:5px;"></a></div>\r\n<input type="hidden" name="CAPTCHA_Postback" id="CAPTCHA_Postback" value="true" />\r\n<div><input type="text" name="securityCode" id="securityCode" size="12" maxlength="5" autocomplete="off" class="Captcha_Input" placeholder="Kodu Yaz"/></div>\r\n<div><input type="button" id="IletisimButonGonder" value="" class="Gonder_Buton"/></div>\r\n</div>\r\n</form>\r\n\r\n</div>\r\n\r\n\r\n<h1 id="Detay_Baslik">Sorulmuş Sorular ve Cevapları</h1>\r\n<div id="Detay_Icerik">\r\n\r\n\r\n \r\n  \r\n\r\n<div id="Soru">\r\n<ul>\r\n\r\n<li>\r\n<div id="Adi"><span>A**** *****</span> sordu,</div>\r\n<div id="Soru">İyi günler hocam ben Malatyalı bir depremzedeyim depremden yaklaşık bir yıl önce topraktan ev satın aldım. Müteahhit ile aramızda bir adı sözleşme yaptık. Noter onaylı değil müteahhit 2 bloklu olan sitenin 1. Tamamen bitirmişti insanlar oturuyordu içinde 2. Blok ise resmi evraklarda yüzde 95 seviyesindeydi. Depremde bu iki blok ağır hasar aldı tapusunu depremden önce alanlar hak sahipliğinden faydalandı ancak benim gibi olan 8 kişi tapuyu depremden sonra almış olduğunuz belirtilerek reddedildi. Ancak ben evi depremden önce aldım bununla ilgili elimde hem adi sözleşme var hemde ödemen depremden önce müteahhit firmanın banka hesabına yaptığım ödemelerin dekontu ve müteahhit firmanın aldığına dair makbuzlar var. Sizce hak sahipliği alabilirmiyim.teşekkürler</div>\r\n<div id="Cevap">\r\n<div class="Resim"><img src="/images/muhasebecevap.jpg"/></div>\r\n<div class="DoktorBilgiler">\r\n<div class="DoktorAdi">YH Grup</div>\r\n<div class="DoktorUnvani">Hukuk Bilgi Platformu</div>\r\n<div class="DoktorCevabi">Merhaba, hak sahipliği için; söz konusu evin ağır hasarlı olması şart değil, orta derecede hasara uğrayan kişiler de hak sahipliği için başvuruda bulunabilir. Hak sahibi olamayacak kişiler: Kanuni sürede talep ve taahhütname vermeyen ve borçlandırma işlemini yapmayanlar ile söz konusu yerde kendisine veya eşine ait aynı cins ikinci hasarsız konutu olanlardır. Sizin durumunuza ilişkin olarak ise; evi depremden önce almış olmanız sebebiyle elinizdeki belgeleri sunarak itiraz başvurusunda bulunabilirsiniz.</div>\r\n</div>\r\n</div>\r\n</li>\r\n\r\n<li>\r\n<div id="Adi"><span>E**** *****</span> sordu,</div>\r\n<div id="Soru">merhaba cevaplarınız için teşekkür ederim.  1 suç : 2016 yılında alkollü araç kullanma 25 gün hapis 500 tl para cezasına çevrildi ve HAGB verildi. 2. suç : 2018 yılında basit yaralama 3000 tl adli para cezası verildi ve 1.suçtaki HAGB bozuldu. parası 2020 ödendi. HAGB bozulan alkollü araç parasıda 2021 aralık ayında ödendi.  3. suç : 2024 ekim silahlı tehdit aralıkta duruşma. bunda tekerrür uygulanırmı  acaba ?</div>\r\n<div id="Cevap">\r\n<div class="Resim"><img src="/images/muhasebecevap.jpg"/></div>\r\n<div class="DoktorBilgiler">\r\n<div class="DoktorAdi">YH Grup</div>\r\n<div class="DoktorUnvani">Hukuk Bilgi Platformu</div>\r\n<div class="DoktorCevabi">Merhaba, TCK madde 58&acute; e göre tekerrür : Önceden işlenen suçtan dolayı verilen hüküm kesinleştikten sonra yeni bir suçun işlenmesi halinde, tekerrür hükümleri uygulanır. Bunun için cezanın infaz edilmiş olması gerekmez. Söz konusu sizin durumunuza ilişkin olarak ise tekerrür hükümleri sadece hapis cezaları hakkında uygulandığı için tekerrür uygulanan sonuç cezanın hapis cezası olması gerekir. Adli para cezası hakkında tekerrür hükümleri\xa0uygulanamaz.</div>\r\n</div>\r\n</div>\r\n</li>\r\n\r\n<li>\r\n<div id="Adi"><span>E**** *****</span> sordu,</div>\r\n<div id="Soru">Merhaba benim amca oğlum var anne babası kardeşi vefat etti amca oğlu yaşlı olduğu için ben ilgileniyorum benden başkada babamın ilk eşinden olan ablam ve rahmetli abimin oğlu var birde halamın çocukları ama bunlar yıllardır gelip görmüyorlar herhangi bir yardımları olmuyor ilgilen miyorlar amca oğluda mirası benden başkasının almasını istemiyor herseiyle ben ilgilenip kosturdugum için nasıl bir şey yapmamız lazım hangi yolu izlememiz gerek yardımcı olurmusunuz </div>\r\n<div id="Cevap">\r\n<div class="Resim"><img src="/images/muhasebecevap.jpg"/></div>\r\n<div class="DoktorBilgiler">\r\n<div class="DoktorAdi">YH Grup</div>\r\n<div class="DoktorUnvani">Hukuk Bilgi Platformu</div>\r\n<div class="DoktorCevabi">Merhaba, vefatı halinde mirasını size bırakmak istediğine dair vasiyetname\xa0yapabilir.</div>\r\n</div>\r\n</div>\r\n</li>\r\n\r\n<li>\r\n<div id="Adi"><span>Y**** *****</span> sordu,</div>\r\n<div id="Soru">7 aydır çalışmış olduğum şirkette 3  kez iş kazası geçirdim ilk kazamda 2 aylık çalışandım ve sigortam olmadığı için tedavi olamadım 2 kazamda elim dikiş derecesinde kesildi ancak işyeri müdürüm iş kazası olarak hastaneye kaydımı yaptırmadı 3 iş kazamda ise demir yük tutucu gözüme çarptı ve gözüm şişti hafif bir şekilde kanadı ancak yine işyeri müdürüm iş kazası olarak hastaneye kaydımı yaptırmadı geriye dönük şikâyette bulunabilirmiyim?</div>\r\n<div id="Cevap">\r\n<div class="Resim"><img src="/images/muhasebecevap.jpg"/></div>\r\n<div class="DoktorBilgiler">\r\n<div class="DoktorAdi">YH Grup</div>\r\n<div class="DoktorUnvani">Hukuk Bilgi Platformu</div>\r\n<div class="DoktorCevabi">Merhaba, işveren; meydana gelen iş kazasını Sosyal Güvenlik Kurumuna bildirmekle yükümlüdür. Bildirimin süresi, kazanın yaşandığı tarihten itibaren 3 iş günüdür. Bu bildirimi yapmayan işveren için şikayette bulunabilirsiniz.</div>\r\n</div>\r\n</div>\r\n</li>\r\n\r\n<li>\r\n<div id="Adi"><span>R**** *****</span> sordu,</div>\r\n<div id="Soru">Merhaba Site yöneticileri iş avansı adı altında site hesplarından kendi şahsi hesaplarina yüksek miktarlarda para transferi yapabilirleri ? . Yapmışlarsa yaptirimi ne olur. Ayrıca siteye alınan bedelleri kendi şahsi kredi kartlarindan taksitle alıp siteden peşin almak hukukimi</div>\r\n<div id="Cevap">\r\n<div class="Resim"><img src="/images/muhasebecevap.jpg"/></div>\r\n<div class="DoktorBilgiler">\r\n<div class="DoktorAdi">YH Grup</div>\r\n<div class="DoktorUnvani">Hukuk Bilgi Platformu</div>\r\n<div class="DoktorCevabi">Merhaba, zimmet sebebine dayanarak site  yöneticilerinin davranışına ilişkin savcılığa suç duyurusunda bulunabilirsiniz.</div>\r\n</div>\r\n</div>\r\n</li>\r\n\r\n<li>\r\n<div id="Adi"><span>F**** *****</span> sordu,</div>\r\n<div id="Soru">Eşimle anlaşmalı boşanma davası açtık dilekçede çocuklar annede kalacaktır ortak velayet ve  nafaka

In [55]:
'''
<div id="Detay_Icerik">


 
  

<div id="Soru">
<ul>

<li>
<div id="Adi"><span>M**** *****</span> sordu,</div>
<div id="Soru">Merhaba. Eşime 3 ay önce boşanma davası açtım eşimin avukatı cevap dilekcesinde tüm kusuru bana yüklemiş davanın reddini talep etmisler. Henüz duruşma tarihi belli olmadı. Benim ağır kusurlu ve haksız olduğumu iddia ederek davayı düşürmeleri mümkün mü?</div>
<div id="Cevap">
<div class="Resim"><img src="/images/muhasebecevap.jpg"></div>
<div class="DoktorBilgiler">
<div class="DoktorAdi">YH Grup</div>
<div class="DoktorUnvani">Hukuk Bilgi Platformu</div>
<div class="DoktorCevabi">Merhaba, boşanma davası açılabilmesi için boşanma davası açan eşin kusursuz veya az kusurlu olması gerekmemektedir. Kusurlu eş de boşanma davası açabilir. Ancak davacının kusuru daha ağır ise, davalının açılan davaya itiraz hakkı bulunmakta olup, boşanmaya karar verilebilmesi için davalı eşin az da olsa kusuru bulunması gerekmektedir. Kural olarak az kusurlu eşin boşanma davasına itiraz etmesi halinde dava reddedilir. Ancak itiraz eden davalı eş, itirazında kötüniyetliyse ve evlilik birliğinin devamında eşler bakımından korunmaya değer bir yarar kalmamışsa boşanmaya karar&nbsp;verilecektir.</div>
</div>
</div>
</li>

<li>
<div id="Adi"><span>E**** *****</span> sordu,</div>
<div id="Soru">Merhaba , Apartmanımız 82 daireli bir apartman ve otoparkı yeterli değil. Sitemizde oturan ve aracı olmayan kat malikleride mevcut.
Aracı olmayan bir kat maliki , aynı blokta oturan bir komşusuna kendi yerini kullanması için izin verebilirmi ?
İzin verilen kat malikinin 1 aracı zaten var , tanıdığından ikinci araç için izin alarak kart okuma sistemi ile otoparka girmekte ve zaman zaman yerimiz olmasına rağmen yer bulamayan diğer kat maliklerini rahatsız etmektedir. Bu konudaki yorumlarınızı rica ediyorum.

Saygılarımla</div>
<div id="Cevap">
<div class="Resim"><img src="/images/muhasebecevap.jpg"></div>
<div class="DoktorBilgiler">
<div class="DoktorAdi">YH Grup</div>
<div class="DoktorUnvani">Hukuk Bilgi Platformu</div>
<div class="DoktorCevabi">Merhaba, tapuda ve yönetim planında her kat maliki için bir otopark verilmediyse yalnızca tapuda ismi geçen daireler otoparktan faydalanabilir. Fakat tapuda kendisine tahsis edilmiş bir otopark alanı bulunan kat maliki dilerse kendi yerini bir komşusunun kullanımı için izin verebilir, bunda bir sakınca bulunmamaktadır.</div>
</div>
</div>
</li>

<li>
<div id="Adi"><span>H**** *****</span> sordu,</div>
<div id="Soru">Ablam 21.10.2024 tarihinde vefat etti.Gerekli belgelerle müracaat ettiğimizde Bankadan kredi çekmiş olduğunu öğrendik. Kontrol ettiğimizde sigortanın teminat ettiği rakam 22 bin muallak rakam 8 bin bankaya ödediği rakam ise 14 bin TL (küsüratları var yuvarladım) Bu durumda arastirmama göre Sigorta teminat ettiği rakamı ödemek zorunda degilmi? Henüz hesabı kapatmadik. Konuyla ilgili yardımcı olabileceğiniz bilgileri vermenizi rica eder,iyi çalışmalar dilerim. Saygılarımla. </div>
<div id="Cevap">
<div class="Resim"><img src="/images/muhasebecevap.jpg"></div>
<div class="DoktorBilgiler">
<div class="DoktorAdi">YH Grup</div>
<div class="DoktorUnvani">Hukuk Bilgi Platformu</div>
<div class="DoktorCevabi">Merhaba, Sigorta teminat ettiği rakamı ödemesi gerekmektedir.</div>
</div>
</div>
</li>

<li>
<div id="Adi"><span>S**** *****</span> sordu,</div>
<div id="Soru">Merhaba. 2000yilinda evlendim.. 2021 yılında bir araç satın aldım. Aracın satın alınması tamamiyle ben ödedim. Yani benim paramla aldık   bir süre sonra işlerin daha kolay yürümesi için eşime vekalet verdim ve aracı onun üzerine geçirdik. Fazla zaman geçmeden benim bilgim olmayan , eşimin biz evlenmeden yıllar önce edindiği vergi borcu yüzünden aracımıza haciz kararı konuldu. Şimdi bosanuyoruz. Ben bu borçtan sorumlu olmadigimi belirtip aracımı geri alabilir miyim , üstündeki haczi kaldırabilir miyim ? Desteğiniz için şimdiden teşekkür ederim. </div>
<div id="Cevap">
<div class="Resim"><img src="/images/muhasebecevap.jpg"></div>
<div class="DoktorBilgiler">
<div class="DoktorAdi">YH Grup</div>
<div class="DoktorUnvani">Hukuk Bilgi Platformu</div>
<div class="DoktorCevabi">Merhaba, evlendikten sonra edinilen mallar eğer mal ayrılığı rejimini seçmediyseniz medeni kanunumuza göre yasal mal rejimi olan edinilmiş mallara katılma rejimine tabidir. Bu rejime göre taşınır veya taşınmaz mal ister sizin üzerinize olsun ister eşinizin üzerine olsun boşanırken yarı yarıya bölüşülmektedir. Bu sebeple eşiniz üzerinde görünen aracınızı geri alabilmeniz için öncelikle borcu ödemeli, haczi kaldırmalısınız.</div>
</div>
</div>
</li>

<li>
<div id="Adi"><span>B**** *****</span> sordu,</div>
<div id="Soru">Yanlışlikla dedeme ait olan bir tarla yeğenin üzerine geçmiş. Yeğeni de bu tarlanın dedeme ait olduğunu kabul etmiş. 3 erkek kardeşin üzerine anlaştiklari kişiye vereceğini diğer ikisinden habersiz başka birine vermeyeceğini beyan etti. 2 amcam da babam üzerinde mutabık kalınca dedemin yeğeni mevzu bahis tarlayı babama satış yaptı. Şuan ise amcamlar bu tarlayı babama vermek istemiyorlar ve dava açarak alacaklarıni söylüyorlar. Herhangi bir para ödemeden bu satış işleminin gerçekleşmesini de delil olarak sunuyorlar. Böyle bir dava açabilirler mi kazanırlar mı</div>
<div id="Cevap">
<div class="Resim"><img src="/images/muhasebecevap.jpg"></div>
<div class="DoktorBilgiler">
<div class="DoktorAdi">YH Grup</div>
<div class="DoktorUnvani">Hukuk Bilgi Platformu</div>
<div class="DoktorCevabi">Merhaba, tapuda herhangi bir satış işlemi gerçekleşirken zaten taraflara alacaklarını alıp almadıkları sorulur. Aldıklarını beyan ettikleri takdirde satış işlemi gerçekleşmektedir. Elbette dava açabilirler fakat ispat yükü kendilerine aittir. Muvazaalı işlemi ispat edebilmeleri&nbsp;gerekir.</div>
</div>
</div>
</li>

<li>
<div id="Adi"><span>N**** *****</span> sordu,</div>
<div id="Soru">TCDD  elektronik bakım müdürlüğünde imal edilen yer magneti ölçüm cihazı  hatalı ölçme yapıyor  hatanın nasıl düzeleceği ile ilgili yaptığım öneriler  dikkate alınmıyor .bu konu ile ilgili olarak savcılığa  görevi kötüye kullan  sebebiyle şikayet edilir mi .Teşekkür ederim</div>
<div id="Cevap">
<div class="Resim"><img src="/images/muhasebecevap.jpg"></div>
<div class="DoktorBilgiler">
<div class="DoktorAdi">YH Grup</div>
<div class="DoktorUnvani">Hukuk Bilgi Platformu</div>
<div class="DoktorCevabi">Merhaba, görevi kötüye kullanma suçunu işleyen kişi; görevin gereklerini ihmal eden veya geciktirerek bir başkasını mağdur eden, kamuyu zarara uğratan kişidir. Söz konusu sizin durumunuza ilişkin olarak da karşı taraf görevin gereklerini ihmal ederek yapılması gereken işi yapmıyorsa şikayette bulunabilirsiniz.</div>
</div>
</div>
</li>

<li>
<div id="Adi"><span>M**** *****</span> sordu,</div>
<div id="Soru">Yakın tarihte maddi hasarlı trafik kazası geçirdim. kazaya karışan 1 araç daha var. iki şeritli yol üzerinde öndeki araç ani fren yapinca sagdan gitmek istedim lakin park yasağı bulunan taşıt yolunda carpmis olduğum araç park halindeydi. tutanak polis tarafından tutuldu ve bugüne sonuçlandı. 52/1-b ihlalinden tüm kusuru bende buldular kaza tutunagindaki aracın park halinde bulunduğunu belirtmelerine rağmen. Karşı tarafa da 60/1-a ihlalinden kusur belirtip oranın 50-50 olması gerekmiyor mu? konu hakkında danışmanlık almak istiyorum ona göre mahkeme aracılığıyla itiraz edeceğim</div>
<div id="Cevap">
<div class="Resim"><img src="/images/muhasebecevap.jpg"></div>
<div class="DoktorBilgiler">
<div class="DoktorAdi">YH Grup</div>
<div class="DoktorUnvani">Hukuk Bilgi Platformu</div>
<div class="DoktorCevabi">Merhaba, söz konusu Kaza Tespit Tutanağına 5 iş günü içerisinde itiraz&nbsp;edebilirsiniz.</div>
</div>
</div>
</li>

<li>
<div id="Adi"><span>D**** *****</span> sordu,</div>
<div id="Soru">Merhabalar. Perakende sektöründe mağaza müdürü olarak çalışıyorum. Yaklaşık 1 ay önce 2 günlük bir eğitimle mağazayı sayımla (devreden müdür / bölge yöneticisinin imzası olmadan) devraldım. Bölge müdürü yeterli eğitimi vermedi (diğer mağaza müdürleri 1 aylık eğitimle mağaza devralırken ben 2 günlük bir eğitimle apar topar geldim) ve hiç destek olmadı. Şartlar bana uymadı deneme süresinin içindeyken istifa edeceğimi söyledim tekrar sayım yapmam gerektiğini söylediler. Bu süre zarfında haftanın 2 günü olmak üzere toplamda 6 sevkiyat aldım ve sistem üzerinden onaylamayı veya eksik sevkiyatı nasıl onaylayacağımı bilmediğimi bildirerek bölge müdürümü bekledim. Benim gibi personellerim de maksimum 1 buçuk aylık çalışanlardı. Sayım günü bir destek mağaza müdürü göndererek ben depoda ürün sayımı yaparken tüm sevkiyatlarım kabul edildi. Buradaki önemli nokta şu; fiziki olarak gelen son sevkiyatta eksik ürün vardı ve sayımın olduğu hafta ürünlerin irsaliyeleri kesildi fakat ürünler sevkten geri döndürüldü. Sayımda 26 saatlik bir çalışmanın sonucu elimize belgeler verildi ve imza attırıldı. Ertesi gün gözden kaçan yerleri bildirdim, sayım ekibinin ve benim ekibimin yeni olduğunu vurgulayarak düzeltme istedim ama düzeltilemez, sayım ekibi profesyonel bir ekip denildi kestirip atıldı. İlk hesaplamama göre 193.000 TL gibi bir açık veriyor mağaza ve bir iki gün içerisinde sayım sonuçları açıklandığında zararı benden talep etmek isteyecekler. Nasıl bir yol izlemem gerektiği konusunda destek rica ederim. </div>
<div id="Cevap">
<div class="Resim"><img src="/images/muhasebecevap.jpg"></div>
<div class="DoktorBilgiler">
<div class="DoktorAdi">YH Grup</div>
<div class="DoktorUnvani">Hukuk Bilgi Platformu</div>
<div class="DoktorCevabi">Merhaba, mağaza müdürü görev ve sorumlulukları arasında ; mağazada satışı arttırmak ve verimliliği sağlamak adına ekip yönetmek, stok seviyelerini yönetmek, mağazanın satış rakamlarını analiz etmek yer almaktadır. Fakat söz konusu sizin durumunuza ilişkin olarak;  bölge müdürünün yeterli eğitimi vermeden sizi mağaza müdürü olarak işe başlatmış olmaları yerinde olmamış. Bu durumu Çalışma ve Sosyal Hizmetler Bakanlığına bildirebilirsiniz.</div>
</div>
</div>
</li>

<li>
<div id="Adi"><span>T**** *****</span> sordu,</div>
<div id="Soru">Merhaba,
Arkadaş ortamında tanıştığım bir kişi ile iş teklifi alıp şirketinde çalışmaya başladım. Kişi ile yakın arkadaş olup aynı zamanda işçisi olarak çalıştım. İşveren olarak gözüken kişinin benden arkadaşlıktan ileri istekleri olduğu için reddettim ve iş akdimi sonlandırdı ve beni yazılı tehditler etmeye başladı. Uyuşturucu madde kullandığını içeren mesajları kayıtlı duruyor. Evimi bir arkadaşı ile silahla basıp arkadaşı olayı sakinleştirdi özür diledi ve şikayetçi olmadım. Evime iki kez asılsız ihbarla polis geldi arayıp neden yaptın dediğimde benim yaptığımı ıspatlayamazsın dedi. İşyerinde çalıştığım 6 ay süre zarfında primlerimi eksiksiz yatırdı ama 4 maaşımı yatırmadı sürekli eski belediye meclis üyesi ve tanıdıkları olmasıyla, “kırmızı reçete kullanıyorum seni vursam ceza almam” sözleriyle korkuttuğu için alacağımı isteyemedim. 6 ay geçti üzerinden Şimdi kendisi bana olmayan asılsız şekilde ilamsız icra takibi başlatmış şirketinin adıyla ve itiraz ettim. İtiraza tekrar dava açmış. Uyaptan baktığımda davaya ekli hiç bir dosya delil yok. Ben şimdi ne yapmalıyım nereye başvurmalıyım bu psikolojik savaşı nasıl şikayetçi olabilirim?</div>
<div id="Cevap">
<div class="Resim"><img src="/images/muhasebecevap.jpg"></div>
<div class="DoktorBilgiler">
<div class="DoktorAdi">YH Grup</div>
<div class="DoktorUnvani">Hukuk Bilgi Platformu</div>
<div class="DoktorCevabi">Merhaba, karşı taraf size icra takibinde bulunmuş, siz de itiraz etmişsiniz ve itirazın iptali davası açmış. Bu süreçten itibaren karşı tarafın söz konusu borcu somut delillerle ispat edebilmesi gerekmektedir. Bundan sonraki sürece dahil olarak öyle bir borcunuz olmadığını mahkemede dile getirmelisiniz. Zaten sizin değil itirazın iptali davası açan tarafın ispat yükü&nbsp;bulunmaktadır.</div>
</div>
</div>
</li>

<li>
<div id="Adi"><span>C**** *****</span> sordu,</div>
<div id="Soru">Merhaba ben Cabbar özcan Gaziantep te bulunan Şölen çikolata yaklaşık 18 yıl çalışan  biriyim bu süre içerisinde son bir buçuk yılı hariç sevilen sayılan yaptığımda yspmadigimla yoneticelerim tarafından takdir gören biriyim taki 20. 05. 2022 ye kadar benim yetkililerim baya vardı bir işçi olarak günlük  raporlamayi fabrikada en üst düzeydeki genel müdür ve genel direktör lune yapardım raporlama konusunda benim üstüm olan müdürlerin o gün raporları  biraz gerçek  olmayan  şekilde yapmaması istediler benimbyok deme şansım yok tu o gün kabul ettim ve raporlamayi verdim bunu fark eden en üst müdürümüz bana küfürler hakeretler hatta fiziksel darp bulundu fabrikada kamera kayıtları da mevcut bende o gün gittim hastaneden darp raporu  aldım darp raporu aldığımı duyan müdürler bundan sonraki süreçte bana mobing uygulanmaya başlandı istifamı yazılma konusunda baskı lar benim şef  olarak çalıştığım  yerden alınıp normal işçi gibi çalıştırmaya başladılar ben pes etmedim 18 yıldır yaptığım iş  15.10 2024 tarihinde üzerime hırsızlık  yaptı diye suçladim bana istifani yaz yoksa sana bu organize ekmek yedirmek dediler bende bende kabul etmedim ve beni işten attılar sonra bağlı  bulunduğumuz polis karakoluna ifadeye çağrıldı ifademi verdim geldim bekliyorum  sizce bunların yaptığı  yaşamı ellerinde olan somut bi kamera vardı var benim oradan elimde poşet  çıkarken  şimdi o poşeti içinde ne vardı diyeceksiniz ben fabrikada geri dönüşüm birimine bakan tek sorumlusu yum benim orada görevim  geri dönüşüme geleni tekrar da üretim kazandırmak geri dönüş mü olmayan mallarimizi sirketin anlaşmalı hayvan çiftliğine göndermek ve bizde şeker çikolata benzeri ürünler açıkta kaldığı zaman guvenlenme böceklerden olur çalışma talimatına göre  bu ürünler diğerlerine zarar vermesin diye üretimden uzlastirilir o poşetin içinde  böceklenmis ürünler  vardı bendebonlari toprak alanına attim konu bu şimdiden teşekkürler 

</div>
<div id="Cevap">
<div class="Resim"><img src="/images/muhasebecevap.jpg"></div>
<div class="DoktorBilgiler">
<div class="DoktorAdi">YH Grup</div>
<div class="DoktorUnvani">Hukuk Bilgi Platformu</div>
<div class="DoktorCevabi">Merhaba, öncelikle bir suç dolayısı ile hüküm verilebilmesi için karşı tarafın söz konusu suçu somut delillerle ispat edebilmesi gerekir. Söz konusu sizin durumunuza ilişkin olarak ise kamerada her ne kadar elinizde poşetle çıkarken görülmenize rağmen fabrikada geri dönüşüm biriminde çalışmanız sebebiyle ve o poşetin içinde böceklenmiş ürünler bulunması sebebiyle  söz konusu size isnat edilen suçu işlediğinizi göstermemektedir. Karakolda ifadenizi vermişsiniz. Bundan sonraki süreçte Cumhuriyet Savcısı gerekli görürse  sizin  ifadenizi tekrar almak isteyebilir. Yaşamış olduğunuz durumu orda da&nbsp;açıklarsınız.</div>
</div>
</div>
</li>
 
</ul>
</div>


 <ul class="sayfalama"><li><a href="/sorucevap/?sayfa=1">1</a></li><li><a href="/sorucevap/?sayfa=2" class="secili">2</a></li><li><a href="/sorucevap/?sayfa=3">3</a></li><li><a href="/sorucevap/?sayfa=4">4</a></li><li><a href="/sorucevap/?sayfa=5">5</a></li><li><a href="/sorucevap/?sayfa=6">6</a></li><li><a href="/sorucevap/?sayfa=7">7</a></li><li><a href="/sorucevap/?sayfa=8">8</a></li><li><a href="/sorucevap/?sayfa=9">9</a></li><li><a href="/sorucevap/?sayfa=10">10</a></li><li><a href="/sorucevap/?sayfa=11">11</a></li><li><a href="/sorucevap/?sayfa=12">12</a></li><li><a href="/sorucevap/?sayfa=13">13</a></li><li><a href="/sorucevap/?sayfa=14">14</a></li><li><a href="/sorucevap/?sayfa=15">15</a></li><li><a href="/sorucevap/?sayfa=16">16</a></li><li><a href="/sorucevap/?sayfa=17">17</a></li><li><a href="/sorucevap/?sayfa=18">18</a></li><li><a href="/sorucevap/?sayfa=19">19</a></li><li><a href="/sorucevap/?sayfa=20">20</a></li><li><a href="/sorucevap/?sayfa=21">21</a></li><li><a href="/sorucevap/?sayfa=22">22</a></li><li><a href="/sorucevap/?sayfa=23">23</a></li><li><a href="/sorucevap/?sayfa=24">24</a></li><li><a href="/sorucevap/?sayfa=25">25</a></li><li><a href="/sorucevap/?sayfa=26">26</a></li><li><a href="/sorucevap/?sayfa=27">27</a></li><li><a href="/sorucevap/?sayfa=28">28</a></li><li><a href="/sorucevap/?sayfa=29">29</a></li><li><a href="/sorucevap/?sayfa=30">30</a></li><li><a href="/sorucevap/?sayfa=31">31</a></li><li><a href="/sorucevap/?sayfa=32">32</a></li><li><a href="/sorucevap/?sayfa=33">33</a></li><li><a href="/sorucevap/?sayfa=34">34</a></li><li><a href="/sorucevap/?sayfa=35">35</a></li><li><a href="/sorucevap/?sayfa=36">36</a></li><li><a href="/sorucevap/?sayfa=37">37</a></li><li><a href="/sorucevap/?sayfa=38">38</a></li><li><a href="/sorucevap/?sayfa=39">39</a></li><li><a href="/sorucevap/?sayfa=40">40</a></li><li><a href="/sorucevap/?sayfa=41">41</a></li><li><a href="/sorucevap/?sayfa=42">42</a></li><li><a href="/sorucevap/?sayfa=43">43</a></li><li><a href="/sorucevap/?sayfa=44">44</a></li><li><a href="/sorucevap/?sayfa=45">45</a></li><li><a href="/sorucevap/?sayfa=46">46</a></li><li><a href="/sorucevap/?sayfa=47">47</a></li><li><a href="/sorucevap/?sayfa=48">48</a></li><li><a href="/sorucevap/?sayfa=49">49</a></li><li><a href="/sorucevap/?sayfa=50">50</a></li><li><a href="/sorucevap/?sayfa=51">51</a></li><li><a href="/sorucevap/?sayfa=52">52</a></li><li><a href="/sorucevap/?sayfa=53">53</a></li><li><a href="/sorucevap/?sayfa=54">54</a></li><li><a href="/sorucevap/?sayfa=55">55</a></li><li><a href="/sorucevap/?sayfa=56">56</a></li><li><a href="/sorucevap/?sayfa=57">57</a></li><li><a href="/sorucevap/?sayfa=58">58</a></li><li><a href="/sorucevap/?sayfa=59">59</a></li><li><a href="/sorucevap/?sayfa=60">60</a></li></ul>




</div>
'''

'\n<div id="Detay_Icerik">\n\n\n \n  \n\n<div id="Soru">\n<ul>\n\n<li>\n<div id="Adi"><span>M**** *****</span> sordu,</div>\n<div id="Soru">Merhaba. Eşime 3 ay önce boşanma davası açtım eşimin avukatı cevap dilekcesinde tüm kusuru bana yüklemiş davanın reddini talep etmisler. Henüz duruşma tarihi belli olmadı. Benim ağır kusurlu ve haksız olduğumu iddia ederek davayı düşürmeleri mümkün mü?</div>\n<div id="Cevap">\n<div class="Resim"><img src="/images/muhasebecevap.jpg"></div>\n<div class="DoktorBilgiler">\n<div class="DoktorAdi">YH Grup</div>\n<div class="DoktorUnvani">Hukuk Bilgi Platformu</div>\n<div class="DoktorCevabi">Merhaba, boşanma davası açılabilmesi için boşanma davası açan eşin kusursuz veya az kusurlu olması gerekmemektedir. Kusurlu eş de boşanma davası açabilir. Ancak davacının kusuru daha ağır ise, davalının açılan davaya itiraz hakkı bulunmakta olup, boşanmaya karar verilebilmesi için davalı eşin az da olsa kusuru bulunması gerekmektedir. Kural olarak az kusurlu eşin boşanma davasına itiraz etmesi halinde dava reddedilir. Ancak itiraz eden davalı eş, itirazında kötüniyetliyse ve evlilik birliğinin devamında eşler bakımından korunmaya değer bir yarar kalmamışsa boşanmaya karar&nbsp;verilecektir.</div>\n</div>\n</div>\n</li>\n\n<li>\n<div id="Adi"><span>E**** *****</span> sordu,</div>\n<div id="Soru">Merhaba , Apartmanımız 82 daireli bir apartman ve otoparkı yeterli değil. Sitemizde oturan ve aracı olmayan kat malikleride mevcut.\nAracı olmayan bir kat maliki , aynı blokta oturan bir komşusuna kendi yerini kullanması için izin verebilirmi ?\nİzin verilen kat malikinin 1 aracı zaten var , tanıdığından ikinci araç için izin alarak kart okuma sistemi ile otoparka girmekte ve zaman zaman yerimiz olmasına rağmen yer bulamayan diğer kat maliklerini rahatsız etmektedir. Bu konudaki yorumlarınızı rica ediyorum.\n\nSaygılarımla</div>\n<div id="Cevap">\n<div class="Resim"><img src="/images/muhasebecevap.jpg"></div>\n<div class="DoktorBilgiler">\n<div class="DoktorAdi">YH Grup</div>\n<div class="DoktorUnvani">Hukuk Bilgi Platformu</div>\n<div class="DoktorCevabi">Merhaba, tapuda ve yönetim planında her kat maliki için bir otopark verilmediyse yalnızca tapuda ismi geçen daireler otoparktan faydalanabilir. Fakat tapuda kendisine tahsis edilmiş bir otopark alanı bulunan kat maliki dilerse kendi yerini bir komşusunun kullanımı için izin verebilir, bunda bir sakınca bulunmamaktadır.</div>\n</div>\n</div>\n</li>\n\n<li>\n<div id="Adi"><span>H**** *****</span> sordu,</div>\n<div id="Soru">Ablam 21.10.2024 tarihinde vefat etti.Gerekli belgelerle müracaat ettiğimizde Bankadan kredi çekmiş olduğunu öğrendik. Kontrol ettiğimizde sigortanın teminat ettiği rakam 22 bin muallak rakam 8 bin bankaya ödediği rakam ise 14 bin TL (küsüratları var yuvarladım) Bu durumda arastirmama göre Sigorta teminat ettiği rakamı ödemek zorunda degilmi? Henüz hesabı kapatmadik. Konuyla ilgili yardımcı olabileceğiniz bilgileri vermenizi rica eder,iyi çalışmalar dilerim. Saygılarımla. </div>\n<div id="Cevap">\n<div class="Resim"><img src="/images/muhasebecevap.jpg"></div>\n<div class="DoktorBilgiler">\n<div class="DoktorAdi">YH Grup</div>\n<div class="DoktorUnvani">Hukuk Bilgi Platformu</div>\n<div class="DoktorCevabi">Merhaba, Sigorta teminat ettiği rakamı ödemesi gerekmektedir.</div>\n</div>\n</div>\n</li>\n\n<li>\n<div id="Adi"><span>S**** *****</span> sordu,</div>\n<div id="Soru">Merhaba. 2000yilinda evlendim.. 2021 yılında bir araç satın aldım. Aracın satın alınması tamamiyle ben ödedim. Yani benim paramla aldık   bir süre sonra işlerin daha kolay yürümesi için eşime vekalet verdim ve aracı onun üzerine geçirdik. Fazla zaman geçmeden benim bilgim olmayan , eşimin biz evlenmeden yıllar önce edindiği vergi borcu yüzünden aracımıza haciz kararı konuldu. Şimdi bosanuyoruz. Ben bu borçtan sorumlu olmadigimi belirtip aracımı geri alabilir miyim , üstündeki haczi kaldırabilir miyim ? Desteğiniz için şimdiden teşekkür ederim. </div>\n<div id="Cevap">\n<div class="Resim"><img src="/images/muhasebecevap.jpg"></div>\n<div class="DoktorBilgiler">\n<div class="DoktorAdi">YH Grup</div>\n<div class="DoktorUnvani">Hukuk Bilgi Platformu</div>\n<div class="DoktorCevabi">Merhaba, evlendikten sonra edinilen mallar eğer mal ayrılığı rejimini seçmediyseniz medeni kanunumuza göre yasal mal rejimi olan edinilmiş mallara katılma rejimine tabidir. Bu rejime göre taşınır veya taşınmaz mal ister sizin üzerinize olsun ister eşinizin üzerine olsun boşanırken yarı yarıya bölüşülmektedir. Bu sebeple eşiniz üzerinde görünen aracınızı geri alabilmeniz için öncelikle borcu ödemeli, haczi kaldırmalısınız.</div>\n</div>\n</div>\n</li>\n\n<li>\n<div id="Adi"><span>B**** *****</span> sordu,</div>\n<div id="Soru">Yanlışlikla dedeme ait olan bir tarla yeğenin üzerine geçmiş. Yeğeni de bu tarlanın dedeme ait olduğunu kabul etmiş. 3 erkek kardeşin üzerine anlaştiklari kişiye vereceğini diğer ikisinden habersiz başka birine vermeyeceğini beyan etti. 2 amcam da babam üzerinde mutabık kalınca dedemin yeğeni mevzu bahis tarlayı babama satış yaptı. Şuan ise amcamlar bu tarlayı babama vermek istemiyorlar ve dava açarak alacaklarıni söylüyorlar. Herhangi bir para ödemeden bu satış işleminin gerçekleşmesini de delil olarak sunuyorlar. Böyle bir dava açabilirler mi kazanırlar mı</div>\n<div id="Cevap">\n<div class="Resim"><img src="/images/muhasebecevap.jpg"></div>\n<div class="DoktorBilgiler">\n<div class="DoktorAdi">YH Grup</div>\n<div class="DoktorUnvani">Hukuk Bilgi Platformu</div>\n<div class="DoktorCevabi">Merhaba, tapuda herhangi bir satış işlemi gerçekleşirken zaten taraflara alacaklarını alıp almadıkları sorulur. Aldıklarını beyan ettikleri takdirde satış işlemi gerçekleşmektedir. Elbette dava açabilirler fakat ispat yükü kendilerine aittir. Muvazaalı işlemi ispat edebilmeleri&nbsp;gerekir.</div>\n</div>\n</div>\n</li>\n\n<li>\n<div id="Adi"><span>N**** *****</span> sordu,</div>\n<div id="Soru">TCDD  elektronik bakım müdürlüğünde imal edilen yer magneti ölçüm cihazı  hatalı ölçme yapıyor  hatanın nasıl düzeleceği ile ilgili yaptığım öneriler  dikkate alınmıyor .bu konu ile ilgili olarak savcılığa  görevi kötüye kullan  sebebiyle şikayet edilir mi .Teşekkür ederim</div>\n<div id="Cevap">\n<div class="Resim"><img src="/images/muhasebecevap.jpg"></div>\n<div class="DoktorBilgiler">\n<div class="DoktorAdi">YH Grup</div>\n<div class="DoktorUnvani">Hukuk Bilgi Platformu</div>\n<div class="DoktorCevabi">Merhaba, görevi kötüye kullanma suçunu işleyen kişi; görevin gereklerini ihmal eden veya geciktirerek bir başkasını mağdur eden, kamuyu zarara uğratan kişidir. Söz konusu sizin durumunuza ilişkin olarak da karşı taraf görevin gereklerini ihmal ederek yapılması gereken işi yapmıyorsa şikayette bulunabilirsiniz.</div>\n</div>\n</div>\n</li>\n\n<li>\n<div id="Adi"><span>M**** *****</span> sordu,</div>\n<div id="Soru">Yakın tarihte maddi hasarlı trafik kazası geçirdim. kazaya karışan 1 araç daha var. iki şeritli yol üzerinde öndeki araç ani fren yapinca sagdan gitmek istedim lakin park yasağı bulunan taşıt yolunda carpmis olduğum araç park halindeydi. tutanak polis tarafından tutuldu ve bugüne sonuçlandı. 52/1-b ihlalinden tüm kusuru bende buldular kaza tutunagindaki aracın park halinde bulunduğunu belirtmelerine rağmen. Karşı tarafa da 60/1-a ihlalinden kusur belirtip oranın 50-50 olması gerekmiyor mu? konu hakkında danışmanlık almak istiyorum ona göre mahkeme aracılığıyla itiraz edeceğim</div>\n<div id="Cevap">\n<div class="Resim"><img src="/images/muhasebecevap.jpg"></div>\n<div class="DoktorBilgiler">\n<div class="DoktorAdi">YH Grup</div>\n<div class="DoktorUnvani">Hukuk Bilgi Platformu</div>\n<div class="DoktorCevabi">Merhaba, söz konusu Kaza Tespit Tutanağına 5 iş günü içerisinde itiraz&nbsp;edebilirsiniz.</div>\n</div>\n</div>\n</li>\n\n<li>\n<div id="Adi"><span>D**** *****</span> sordu,</div>\n<div id="Soru">Merhabalar. Perakende sektöründe mağaza müdürü olarak çalışıyorum. Yaklaşık 1 ay önce 2 günlük bir eğitimle mağazayı sayımla (devreden müdür / bölge yöneticisinin imzası olmadan) devraldım. Bölge müdürü yeterli eğitimi vermedi (diğer mağaza müdürleri 1 aylık eğitimle mağaza devralırken ben 2 günlük bir eğitimle apar topar geldim) ve hiç destek olmadı. Şartlar bana uymadı deneme süresinin içindeyken istifa edeceğimi söyledim tekrar sayım yapmam gerektiğini söylediler. Bu süre zarfında haftanın 2 günü olmak üzere toplamda 6 sevkiyat aldım ve sistem üzerinden onaylamayı veya eksik sevkiyatı nasıl onaylayacağımı bilmediğimi bildirerek bölge müdürümü bekledim. Benim gibi personellerim de maksimum 1 buçuk aylık çalışanlardı. Sayım günü bir destek mağaza müdürü göndererek ben depoda ürün sayımı yaparken tüm sevkiyatlarım kabul edildi. Buradaki önemli nokta şu; fiziki olarak gelen son sevkiyatta eksik ürün vardı ve sayımın olduğu hafta ürünlerin irsaliyeleri kesildi fakat ürünler sevkten geri döndürüldü. Sayımda 26 saatlik bir çalışmanın sonucu elimize belgeler verildi ve imza attırıldı. Ertesi gün gözden kaçan yerleri bildirdim, sayım ekibinin ve benim ekibimin yeni olduğunu vurgulayarak düzeltme istedim ama düzeltilemez, sayım ekibi profesyonel bir ekip denildi kestirip atıldı. İlk hesaplamama göre 193.000 TL gibi bir açık veriyor mağaza ve bir iki gün içerisinde sayım sonuçları açıklandığında zararı benden talep etmek isteyecekler. Nasıl bir yol izlemem gerektiği konusunda destek rica ederim. </div>\n<div id="Cevap">\n<div class="Resim"><img src="/images/muhasebecevap.jpg"></div>\n<div class="DoktorBilgiler">\n<div class="DoktorAdi">YH Grup</div>\n<div class="DoktorUnvani">Hukuk Bilgi Platformu</div>\n<div class="DoktorCevabi">Merhaba, mağaza müdürü görev ve sorumlulukları arasında ; mağazada satışı arttırmak ve verimliliği sağlamak adına ekip yönetmek, stok seviyelerini yönetmek, mağazanın satış rakamlarını analiz etmek yer almaktadır. Fakat söz konusu sizin durumunuza ilişkin olarak;  bölge müdürünün yeterli eğitimi vermeden sizi mağaza müdürü olarak işe başlatmış olmaları yerinde olmamış. Bu durumu Çalışma ve Sosyal Hizmetler Bakanlığına bildirebilirsiniz.</div>\n</div>\n</div>\n</li>\n\n<li>\n<div id="Adi"><span>T**** *****</span> sordu,</div>\n<div id="Soru">Merhaba,\nArkadaş ortamında tanıştığım bir kişi ile iş teklifi alıp şirketinde çalışmaya başladım. Kişi ile yakın arkadaş olup aynı zamanda işçisi olarak çalıştım. İşveren olarak gözüken kişinin benden arkadaşlıktan ileri istekleri olduğu için reddettim ve iş akdimi sonlandırdı ve beni yazılı tehditler etmeye başladı. Uyuşturucu madde kullandığını içeren mesajları kayıtlı duruyor. Evimi bir arkadaşı ile silahla basıp arkadaşı olayı sakinleştirdi özür diledi ve şikayetçi olmadım. Evime iki kez asılsız ihbarla polis geldi arayıp neden yaptın dediğimde benim yaptığımı ıspatlayamazsın dedi. İşyerinde çalıştığım 6 ay süre zarfında primlerimi eksiksiz yatırdı ama 4 maaşımı yatırmadı sürekli eski belediye meclis üyesi ve tanıdıkları olmasıyla, “kırmızı reçete kullanıyorum seni vursam ceza almam” sözleriyle korkuttuğu için alacağımı isteyemedim. 6 ay geçti üzerinden Şimdi kendisi bana olmayan asılsız şekilde ilamsız icra takibi başlatmış şirketinin adıyla ve itiraz ettim. İtiraza tekrar dava açmış. Uyaptan baktığımda davaya ekli hiç bir dosya delil yok. Ben şimdi ne yapmalıyım nereye başvurmalıyım bu psikolojik savaşı nasıl şikayetçi olabilirim?</div>\n<div id="Cevap">\n<div class="Resim"><img src="/images/muhasebecevap.jpg"></div>\n<div class="DoktorBilgiler">\n<div class="DoktorAdi">YH Grup</div>\n<div class="DoktorUnvani">Hukuk Bilgi Platformu</div>\n<div class="DoktorCevabi">Merhaba, karşı taraf size icra takibinde bulunmuş, siz de itiraz etmişsiniz ve itirazın iptali davası açmış. Bu süreçten itibaren karşı tarafın söz konusu borcu somut delillerle ispat edebilmesi gerekmektedir. Bundan sonraki sürece dahil olarak öyle bir borcunuz olmadığını mahkemede dile getirmelisiniz. Zaten sizin değil itirazın iptali davası açan tarafın ispat yükü&nbsp;bulunmaktadır.</div>\n</div>\n</div>\n</li>\n\n<li>\n<div id="Adi"><span>C**** *****</span> sordu,</div>\n<div id="Soru">Merhaba ben Cabbar özcan Gaziantep te bulunan Şölen çikolata yaklaşık 18 yıl çalışan  biriyim bu süre içerisinde son bir buçuk yılı hariç sevilen sayılan yaptığımda yspmadigimla yoneticelerim tarafından takdir gören biriyim taki 20. 05. 2022 ye kadar benim yetkililerim baya vardı bir işçi olarak günlük  raporlamayi fabrikada en üst düzeydeki genel müdür ve genel direktör lune yapardım raporlama konusunda benim üstüm olan müdürlerin o gün raporları  biraz gerçek  olmayan  şekilde yapmaması istediler benimbyok deme şansım yok tu o gün kabul ettim ve raporlamayi verdim bunu fark eden en üst müdürümüz bana küfürler hakeretler hatta fiziksel darp bulundu fabrikada kamera kayıtları da mevcut bende o gün gittim hastaneden darp raporu  aldım darp raporu aldığımı duyan müdürler bundan sonraki süreçte bana mobing uygulanmaya başlandı istifamı yazılma konusunda baskı lar benim şef  olarak çalıştığım  yerden alınıp normal işçi gibi çalıştırmaya başladılar ben pes etmedim 18 yıldır yaptığım iş  15.10 2024 tarihinde üzerime hırsızlık  yaptı diye suçladim bana istifani yaz yoksa sana bu organize ekmek yedirmek dediler bende bende kabul etmedim ve beni işten attılar sonra bağlı  bulunduğumuz polis karakoluna ifadeye çağrıldı ifademi verdim geldim bekliyorum  sizce bunların yaptığı  yaşamı ellerinde olan somut bi kamera vardı var benim oradan elimde poşet  çıkarken  şimdi o poşeti içinde ne vardı diyeceksiniz ben fabrikada geri dönüşüm birimine bakan tek sorumlusu yum benim orada görevim  geri dönüşüme geleni tekrar da üretim kazandırmak geri dönüş mü olmayan mallarimizi sirketin anlaşmalı hayvan çiftliğine göndermek ve bizde şeker çikolata benzeri ürünler açıkta kaldığı zaman guvenlenme böceklerden olur çalışma talimatına göre  bu ürünler diğerlerine zarar vermesin diye üretimden uzlastirilir o poşetin içinde  böceklenmis ürünler  vardı bendebonlari toprak alanına attim konu bu şimdiden teşekkürler \n\n</div>\n<div id="Cevap">\n<div class="Resim"><img src="/images/muhasebecevap.jpg"></div>\n<div class="DoktorBilgiler">\n<div class="DoktorAdi">YH Grup</div>\n<div class="DoktorUnvani">Hukuk Bilgi Platformu</div>\n<div class="DoktorCevabi">Merhaba, öncelikle bir suç dolayısı ile hüküm verilebilmesi için karşı tarafın söz konusu suçu somut delillerle ispat edebilmesi gerekir. Söz konusu sizin durumunuza ilişkin olarak ise kamerada her ne kadar elinizde poşetle çıkarken görülmenize rağmen fabrikada geri dönüşüm biriminde çalışmanız sebebiyle ve o poşetin içinde böceklenmiş ürünler bulunması sebebiyle  söz konusu size isnat edilen suçu işlediğinizi göstermemektedir. Karakolda ifadenizi vermişsiniz. Bundan sonraki süreçte Cumhuriyet Savcısı gerekli görürse  sizin  ifadenizi tekrar almak isteyebilir. Yaşamış olduğunuz durumu orda da&nbsp;açıklarsınız.</div>\n</div>\n</div>\n</li>\n \n</ul>\n</div>\n\n\n <ul class="sayfalama"><li><a href="/sorucevap/?sayfa=1">1</a></li><li><a href="/sorucevap/?sayfa=2" class="secili">2</a></li><li><a href="/sorucevap/?sayfa=3">3</a></li><li><a href="/sorucevap/?sayfa=4">4</a></li><li><a href="/sorucevap/?sayfa=5">5</a></li><li><a href="/sorucevap/?sayfa=6">6</a></li><li><a href="/sorucevap/?sayfa=7">7</a></li><li><a href="/sorucevap/?sayfa=8">8</a></li><li><a href="/sorucevap/?sayfa=9">9</a></li><li><a href="/sorucevap/?sayfa=10">10</a></li><li><a href="/sorucevap/?sayfa=11">11</a></li><li><a href="/sorucevap/?sayfa=12">12</a></li><li><a href="/sorucevap/?sayfa=13">13</a></li><li><a href="/sorucevap/?sayfa=14">14</a></li><li><a href="/sorucevap/?sayfa=15">15</a></li><li><a href="/sorucevap/?sayfa=16">16</a></li><li><a href="/sorucevap/?sayfa=17">17</a></li><li><a href="/sorucevap/?sayfa=18">18</a></li><li><a href="/sorucevap/?sayfa=19">19</a></li><li><a href="/sorucevap/?sayfa=20">20</a></li><li><a href="/sorucevap/?sayfa=21">21</a></li><li><a href="/sorucevap/?sayfa=22">22</a></li><li><a href="/sorucevap/?sayfa=23">23</a></li><li><a href="/sorucevap/?sayfa=24">24</a></li><li><a href="/sorucevap/?sayfa=25">25</a></li><li><a href="/sorucevap/?sayfa=26">26</a></li><li><a href="/sorucevap/?sayfa=27">27</a></li><li><a href="/sorucevap/?sayfa=28">28</a></li><li><a href="/sorucevap/?sayfa=29">29</a></li><li><a href="/sorucevap/?sayfa=30">30</a></li><li><a href="/sorucevap/?sayfa=31">31</a></li><li><a href="/sorucevap/?sayfa=32">32</a></li><li><a href="/sorucevap/?sayfa=33">33</a></li><li><a href="/sorucevap/?sayfa=34">34</a></li><li><a href="/sorucevap/?sayfa=35">35</a></li><li><a href="/sorucevap/?sayfa=36">36</a></li><li><a href="/sorucevap/?sayfa=37">37</a></li><li><a href="/sorucevap/?sayfa=38">38</a></li><li><a href="/sorucevap/?sayfa=39">39</a></li><li><a href="/sorucevap/?sayfa=40">40</a></li><li><a href="/sorucevap/?sayfa=41">41</a></li><li><a href="/sorucevap/?sayfa=42">42</a></li><li><a href="/sorucevap/?sayfa=43">43</a></li><li><a href="/sorucevap/?sayfa=44">44</a></li><li><a href="/sorucevap/?sayfa=45">45</a></li><li><a href="/sorucevap/?sayfa=46">46</a></li><li><a href="/sorucevap/?sayfa=47">47</a></li><li><a href="/sorucevap/?sayfa=48">48</a></li><li><a href="/sorucevap/?sayfa=49">49</a></li><li><a href="/sorucevap/?sayfa=50">50</a></li><li><a href="/sorucevap/?sayfa=51">51</a></li><li><a href="/sorucevap/?sayfa=52">52</a></li><li><a href="/sorucevap/?sayfa=53">53</a></li><li><a href="/sorucevap/?sayfa=54">54</a></li><li><a href="/sorucevap/?sayfa=55">55</a></li><li><a href="/sorucevap/?sayfa=56">56</a></li><li><a href="/sorucevap/?sayfa=57">57</a></li><li><a href="/sorucevap/?sayfa=58">58</a></li><li><a href="/sorucevap/?sayfa=59">59</a></li><li><a href="/sorucevap/?sayfa=60">60</a></li></ul>\n\n\n\n\n</div>\n'

In [56]:
tum_sorular = []

In [57]:
'''soru_dict dedigimiz sey;
{
"soru": "soru_metni",
"cevap": "cevap_metni",
"cevaplayan_unvan": "cevaplayanın_adı"

}
'''

'soru_dict dedigimiz sey;\n{\n"soru": "soru_metni",\n"cevap": "cevap_metni",\n"cevaplayan_unvan": "cevaplayanın_adı"\n\n}\n'

In [58]:
def temizle(metin):
    return metin.replace("\n", " ").replace("\t", " ").replace("\r", " ").strip()
    while "  " in metin:
        metin = metin.replace("  ", " ")
    return metin.strip()

In [59]:
tum_sorular = [] # her defasında sıfırlamamızı saglıyor
for i in range(1, 37):
    response = requests.get('https://www.hukuksorucevap.com.tr/sorucevap/?sayfa=' + str(i))
    response.encoding = 'utf-8'

    soup = BeautifulSoup(response.text, 'html.parser')
    soru = soup.find('div', {'id': 'Soru'})
    # len(soru)
    sorular = soru.findAll('li')
    len(sorular)
    for soru_li in sorular:
        soru_dict = {}
        soru_metni = soru_li.find('div', {'id': 'Soru'}).text
        soru_dict['soru'] = temizle(soru_metni)

        cevap_metni = soru_li.find('div', {'id': 'Cevap'}).find('div', {'class': 'DoktorCevabi'}).text
        soru_dict['cevap'] = temizle(cevap_metni)

        cevaplayan_unvan = soru_li.find('div', {'id': 'Cevap'}).find('div', {'class': 'DoktorUnvani'}).text
        soru_dict['cevaplayan_unvan'] = temizle(cevaplayan_unvan)
    
        tum_sorular.append((soru_dict))

len(tum_sorular)

360

In [60]:
# convert tum_sorular to a DataFrame
df = pd.DataFrame(tum_sorular)
df

,soru,cevap,cevaplayan_unvan
0,İyi günler hocam ben Malatyalı bir depremzedey...,"Merhaba, hak sahipliği için; söz konusu evin a...",Hukuk Bilgi Platformu
1,merhaba cevaplarınız için teşekkür ederim. 1 ...,"Merhaba, TCK madde 58´ e göre tekerrür : Önced...",Hukuk Bilgi Platformu
2,Merhaba benim amca oğlum var anne babası karde...,"Merhaba, vefatı halinde mirasını size bırakmak...",Hukuk Bilgi Platformu
3,7 aydır çalışmış olduğum şirkette 3 kez iş ka...,"Merhaba, işveren; meydana gelen iş kazasını So...",Hukuk Bilgi Platformu
4,Merhaba Site yöneticileri iş avansı adı altınd...,"Merhaba, zimmet sebebine dayanarak site yönet...",Hukuk Bilgi Platformu
...,...,...,...
355,11 yıllık bır calısma sonrasında iş yerınden k...,"Merhaba, bu konuya ilişkin olarak tazminatınız...",Hukuk Bilgi Platformu
356,"Sözleşmede, müteahhit tarafından ""imar durumun...","Merhaba, söz konusu sizin durumunuzda bu değiş...",Hukuk Bilgi Platformu
357,Saglik kurulundan bel fitigindan rapor aldim i...,"Merhaba, İş Kanununun 24.maddesine göre işçi, ...",Hukuk Bilgi Platformu
358,12 ayın 26´sı 2023´te 2007 model Ford Focus ar...,"Merhaba, satıcının araçla ilgili vaat ettiğini...",Hukuk Bilgi Platformu
359,2021 6. ayında farklı bankalardan kredi ve kre...,"Merhaba, eşlerden birinin borcundan dolayı hac...",Hukuk Bilgi Platformu

In [62]:
df.to_csv('hukuksorucevap.csv', index=False, encoding='utf-8')

In [63]:
df_csv = pd.read_csv('hukuksorucevap.csv')
df_csv

,soru,cevap,cevaplayan_unvan
0,İyi günler hocam ben Malatyalı bir depremzedey...,"Merhaba, hak sahipliği için; söz konusu evin a...",Hukuk Bilgi Platformu
1,merhaba cevaplarınız için teşekkür ederim. 1 ...,"Merhaba, TCK madde 58´ e göre tekerrür : Önced...",Hukuk Bilgi Platformu
2,Merhaba benim amca oğlum var anne babası karde...,"Merhaba, vefatı halinde mirasını size bırakmak...",Hukuk Bilgi Platformu
3,7 aydır çalışmış olduğum şirkette 3 kez iş ka...,"Merhaba, işveren; meydana gelen iş kazasını So...",Hukuk Bilgi Platformu
4,Merhaba Site yöneticileri iş avansı adı altınd...,"Merhaba, zimmet sebebine dayanarak site yönet...",Hukuk Bilgi Platformu
...,...,...,...
355,11 yıllık bır calısma sonrasında iş yerınden k...,"Merhaba, bu konuya ilişkin olarak tazminatınız...",Hukuk Bilgi Platformu
356,"Sözleşmede, müteahhit tarafından ""imar durumun...","Merhaba, söz konusu sizin durumunuzda bu değiş...",Hukuk Bilgi Platformu
357,Saglik kurulundan bel fitigindan rapor aldim i...,"Merhaba, İş Kanununun 24.maddesine göre işçi, ...",Hukuk Bilgi Platformu
358,12 ayın 26´sı 2023´te 2007 model Ford Focus ar...,"Merhaba, satıcının araçla ilgili vaat ettiğini...",Hukuk Bilgi Platformu
359,2021 6. ayında farklı bankalardan kredi ve kre...,"Merhaba, eşlerden birinin borcundan dolayı hac...",Hukuk Bilgi Platformu